version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    
  
  frontend:
    container_name: appliance-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
    
  
  # api:
  #   build:
  #     context: ./
  #     target: production
  #   image: uncle-api
  #   depends_on:
  #     - db
  #   ports:
  #     - 3001:3001
  #   environment:
  #     NODE_ENV: production
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: postgres
  #   volumes:
  #     - ./:/src
  #     - /src/node_modules
  # redis:
  #   restart: always
  #   image: redis:7.0.5-alpine 
  #   expose:
  #   - 6379
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
volumes:
  db:
    driver: local